site_name: CoreGamesJsDocs
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: cyan
      accent: teal

  text: Roboto
  code: Lato
  logo: https://cdn.discordapp.com/attachments/753043099839758348/847832200421310495/Logo.png
  favicon: https://cdn.discordapp.com/attachments/753043099839758348/847832200421310495/Logo.png
